CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create schema if not exists user_service;

create table if not exists user_service.users  (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   uuid UUID,
   name VARCHAR(255),
   registered_at date,
   email VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id),
   CONSTRAINT uc_users_uuid UNIQUE (uuid)
);

comment on column user_service.users.id is 'Уникальный идентификатор для каждого класса';
comment on column user_service.users.uuid is 'Глобальный идентификатор пользователя';
comment on column user_service.users.name is 'Имя пользователя';
comment on column user_service.users.registered_at is 'Дата регистрации';
comment on column user_service.users.email is 'Email пользователя';