create schema user_service;

create table user_service.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   uuid UUID,
   name VARCHAR(255),
   registered_at date,
   email VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);

alter table user_service.users add CONSTRAINT uc_users_uuid UNIQUE (uuid);