spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: userService
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/shop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    user: postgres
    password: postgres
    schemas: user_service
    url: jdbc:postgresql://localhost:5432/shop
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
server:
  port: 8082