
spring:
  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    url: jdbc:postgresql://10.53.16.4:5432/shop
    user: postgres
    password: KooKo_099
    schemas: public
    sql-migration-prefix: V
    enabled: true

    baseline-on-migrate: true
    #validate-on-migrate: true
    driver-class-name: org.postgresql.Driver
    locations: db/migration
    create-schemas: true

  datasource:
    url: jdbc:postgresql://10.53.16.4:5432/shop
    username: postgres
    password: KooKo_099
    driver-class-name: org.postgresql.Driver

