name: Test
on:
  push:
    branches:
      - 'task/**'
jobs:
  userServiceTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Maven UserService Package
        working-directory: ./userService/
        run: mvn -B clean package -DskipTests
      - name: Run UserService Tests
        working-directory: ./userService/
        run: mvn -B test --file pom.xml
  orderServiceTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Maven OrderService Package
        working-directory: ./orderService/
        run: mvn -B clean package -DskipTests
      - name: Run OrderService Tests
        working-directory: ./orderService/
        run: mvn -B test --file pom.xml
  userServiceCheckstyle:
    runs-on: ubuntu-latest
    needs: userServiceTests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Checkstyle for UserService
        working-directory: ./userService/
        run: mvn -P check-code-style validate
  orderServiceCheckstyle:
    runs-on: ubuntu-latest
    needs: userServiceCheckstyle
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Checkstyle for OrderService
        working-directory: ./orderService/
        run: mvn -P check-code-style validate
  metricsServiceCheckstyle:
    runs-on: ubuntu-latest
    needs: orderServiceCheckstyle
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Checkstyle for MetricsService
        working-directory: ./metricsService/
        run: mvn -P check-code-style validate